[WIP] Add a role to install Jenkins
Sadly, this fails when trying to install the package because of the
error:
```
ERROR: No Java executable found in current PATH:
/bin:/usr/bin:/sbin:/usr/sbin
```